spring:
  application:
    name: studentsapp
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: 233444
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect # !deprecated
    show-sql: true
    properties:
      hibernate:
        format_sql: true